server:
  port: 7000

spring:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:shopping_service;DB_CLOSE_DELAY=-1
    username: sa
    password: sa
  h2:
    console.enabled: true
    console.path: /h2-console
    console.settings.web-allow-others: true
  kafka:
    bootstrap-servers: ${KAFKA_SERVER_NAME}:${KAFKA_SERVER_PORT}
  jackson:
    default-property-inclusion: non-null

logging:
  level:
    org.springframework: ERROR
    com.github.leandrochp.shoppingservice: DEBUG
  pattern:
    console: "[%d{dd-MM-yyyy HH:mm:ss.SSS}] - %msg%n"
    file: "[%d{dd-MM-yyyy HH:mm:ss.SSS}] [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: app.log
